version: "3.2"
services:
  php:
    build: './docker/php/'
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
  apache:
    build: './docker/apache/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
networks:
  frontend:
  backend: